### ISSUE TITLE
Should have the option to disable when in development

### ISSUE THREAD

**Issue by nethunter** [daliborgogic/nuxt-brotli#1]

**Comment by daliborgogic** [comment]
@nethunter Thank you for opening issue. Done [#L7](https://github.com/daliborgogic/nuxt-brotli/blob/40cb8e71be926e0fe374938e87effdaf1dad6a8c/lib/module.js#L7)

**Comment by nethunter** [comment]
Thank you for the quick response!
David Tabachnikov

{ "title" : "Development Process Manager",
  "email" : "david.tabachnikov@gmail.com",
  "voice" : "+972-54-445-1994",
  "skype" :  "NetHuntik",
  "twitter" : "@davidtab" }
